


import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

import dynamic_subjtable.Header;

public class Table extends javax.swing.JFrame {

	private javax.swing.JScrollPane jScrollPane1;

	private dynamic_subjtable.TableCustom tableCustom1;

	public Table() {

		initComponents();

		// Test Data

		init();

	}

	private void init() {

		DefaultTableModel model = (DefaultTableModel) tableCustom1.getModel();

		model.addRow(new Object[] { 1, "John", "$ 150", getSubTableData() });

		model.addRow(new Object[] { 1, "Name", "$ 200", getSubTableData() });

		tableCustom1.autoRowHeight(tableCustom1);

	}

	public DefaultTableModel getSubTableData() {
		DefaultTableModel data = new DefaultTableModel();
		data.setColumnCount(4);
		data.addRow(new Object[] { new Header("No", 10), new Header("Item"), new Header("Total", 200),
				new Header("Detail", 200) });
		data.addRow(new Object[] { 1, "ABC", "$ 50", getSubTableData1() });
		data.addRow(new Object[] { 1, "Vital", "$ 70", getSubTableData1() });
		data.addRow(new Object[] { 1, "Fanta", "$ 20", getSubTableData1() });
		data.addRow(new Object[] { 1, "Coca", getSubTableData1(), getSubTableData1() });
		return data;
	}

	public DefaultTableModel getSubTableData1() {
		DefaultTableModel data = new DefaultTableModel();
		data.setColumnCount(3);
		data.addRow(new Object[] { new Header("No", 10), new Header("Type"), new Header("Qty") });
		data.addRow(new Object[] { 1, "Unit", "50" });
		data.addRow(new Object[] { 1, "Case", "70" });
		data.addRow(new Object[] { 1, "Box", "3" });
		return data;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		tableCustom1 = new dynamic_subjtable.TableCustom();

		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

		tableCustom1.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "No", "Customer", "Total Amount", "Product List" }));
		jScrollPane1.setViewportView(tableCustom1);
		if (tableCustom1.getColumnModel().getColumnCount() > 0) {
			tableCustom1.getColumnModel().getColumn(3).setPreferredWidth(500);
		}

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.TRAILING).addGroup(Alignment.LEADING,
				layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 1037, Short.MAX_VALUE)
						.addContainerGap()));
		layout.setVerticalGroup(
				layout.createParallelGroup(Alignment.TRAILING).addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE).addContainerGap()));
		getContentPane().setLayout(layout);

		pack();

		setLocationRelativeTo(null);

	}

}
